spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nnpia
    connectionProperties: useUnicode=true;characterEncoding=utf8mb4_czech_ci
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.mysql.MySQL5SpatialDialect
server:
  error:
    include-message: always

loizenai:
  app:
    jwtSecret: jwtLoizenai.comSecretKey
    jwtExpiration: 86400